/home/carlos/Embedded/efinity/2023.2/bin/efx_map --project "top" --root "top" --write-efx-verilog "outflow/top.map.v" --write-premap-module "outflow/top.elab.vdb" --binary-db "outflow/top.vdb" --device "T20Q144" --family "Trion" --veri_option "verilog_mode=verilog_2k,vhdl_mode=vhdl_2008" --work-dir "work_syn" --output-dir "outflow" --project-xml "top.xml" --I "."




/home/carlos/Embedded/efinity/2023.2/bin/efx_pnr --circuit "top" --family "Trion" --device "T20Q144" --operating_conditions "C3" --pack --place --vdb_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow/top.vdb" --use_vdb_file "on" --place_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow/top.place" --route_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow/top.route" --sdc_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/top.sdc" --sync_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow/top.interface.csv" --seed "1" --placer_effort_level "2" --max_threads "-1" --print_critical_path "10" --work_dir "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/work_pnr" --output_dir "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow" --timing_analysis "on" --load_delay_matrix
Thu September 12 24 08:55:42 - Running /home/carlos/Embedded/efinity/2023.2/bin/efx_pnr...



/home/carlos/Embedded/efinity/2023.2/bin/efx_pnr --circuit "top" --family "Trion" --device "T20Q144" --operating_conditions "C3" --pack --place --vdb_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow/top.vdb" --use_vdb_file "on" --place_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow/top.place" --route_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow/top.route" --sdc_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/top.sdc" --sync_file "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow/top.interface.csv" --seed "1" --placer_effort_level "2" --max_threads "-1" --print_critical_path "10" --work_dir "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/work_pnr" --output_dir "/Work/Proyects/ecb_T8_T113/migen_tutorial/blink/build/gateware/outflow" --timing_analysis "on" --load_delay_matrix
Thu September 12 24 08:55:42 - Running /home/carlos/Embedded/efinity/2023.2/bin/efx_pnr...


openFPGALoader -b trion_t120_bga576  outflow/top.bit

